import { test, expect } from "@playwright/test";
import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
const url = process.env.BACKUP_TEST_URL ?? "http://localhost:3000/espn-backup";

test("manual picks, rules, persistence, and a downloaded copy work without network", async ({ page, context }) => {
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  await page.goto(url);
  await expect(page.getByRole("heading", { name: "Draft backup", exact: true })).toBeVisible();
  await expect(page.getByText("1 PPR · 12 teams · Pick 7 · 16 rounds")).toBeVisible();
  await expect(page.getByLabel("Reception (PPR)")).toBeHidden();
  await page.getByRole("button", { name: "Overall", exact: true }).click();
  const first = page.locator("tr[data-player]").first();
  const id = await first.getAttribute("data-player");
  const name = await first.locator("strong").textContent();
  const points = await first.locator("td").nth(3).innerText();
  await first.getByRole("button", { name: `Mine: ${name}`, exact: true }).click();
  await expect(page.locator(`tr[data-player="${id}"]`)).toHaveCount(0);
  await page.getByRole("button", { name: "PTS", exact: true }).first().click();
  await page.getByRole("button", { name: "Show drafted", exact: true }).click();
  await expect(page.getByRole("button", { name: "PTS", exact: true }).first()).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator(`tr[data-player="${id}"]`)).toHaveClass(/\bmine\b/);
  await page.getByRole("button", { name: "League rules ▾", exact: true }).click();
  await page.getByLabel("Reception (PPR)").fill("0");
  await page.getByRole("button", { name: "Apply rules", exact: true }).click();
  await expect(page.locator(`tr[data-player="${id}"] td`).nth(3)).not.toHaveText(points);
  await page.getByLabel("Teams", { exact: true }).fill("6");
  await page.getByRole("button", { name: "Apply rules", exact: true }).click();
  await expect(page.getByText("Pick must not exceed team count.")).toBeVisible();
  await page.getByRole("button", { name: "Restore wife’s rules", exact: true }).click();
  await expect(page.getByText("1 PPR · 12 teams · Pick 7 · 16 rounds")).toBeVisible();
  await expect(page.locator(`tr[data-player="${id}"]`)).toHaveClass(/\bmine\b/);
  await page.reload();
  await expect(page.getByText("My roster 1/16", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Save & reference ▾", exact: true }).click();
  const exportPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export picks", exact: true }).click();
  const exported = await exportPromise;
  const directory = await mkdtemp(path.join(tmpdir(), "draft-backup-test-"));
  const progressPath = path.join(directory, "picks.json");
  await exported.saveAs(progressPath);
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download offline copy", exact: true }).click();
  const downloaded = await downloadPromise;
  const htmlPath = path.join(directory, "draft-backup.html");
  await downloaded.saveAs(htmlPath);
  expect((await readFile(htmlPath, "utf8")).includes('id="sheet-app"')).toBe(true);
  await context.setOffline(true);
  await page.goto(pathToFileURL(htmlPath).href);
  await expect(page.getByRole("heading", { name: "Draft backup", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Save & reference ▾", exact: true }).click();
  await page.getByLabel("Import picks", { exact: true }).setInputFiles(progressPath);
  await expect(page.getByText("My roster 1/16", { exact: true })).toBeVisible();
  await page.getByLabel("Import picks", { exact: true }).setInputFiles({ name: "bad.json", mimeType: "application/json", buffer: Buffer.from('{"version":1,"marks":{}}') });
  await expect(page.getByRole("status")).toContainText("Could not import");
  await expect(page.getByText("My roster 1/16", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "My roster", exact: true }).click();
  await page.locator(`tr[data-player="${id}"]`).getByRole("button", { name: `Mine: ${name}`, exact: true }).click();
  await expect(page.getByText("My roster 0/16", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByText("My roster 1/16", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
